# Generated by Django 4.1.5 on 2023-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_urun_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='fiyat',
            field=models.FloatField(),
        ),
    ]
