# Generated by Django 4.1.5 on 2023-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_alter_urun_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='marka',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
